agileProject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gallery/', include('gallery.urls', namespace="images")),
]

gallery/urls.py
from django.conf.urls import url

from . import views

app_name = 'agileProject'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add_image, name='addImage'),
]

gallery/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.
class Image(models.Model):
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=1000)
    description = models.CharField(max_length=1000, null=True)
    type = models.CharField(max_length=5, blank=True)
    imageFile = models.ImageField(upload_to='images', null=True)

    def __str__(self):
        return 'Image: ' + self.name


class ImageForm(ModelForm):
    class Meta:
        model = Image
        fields = ['name', 'url', 'description', 'type', 'imageFile']

gallery/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Image, ImageForm
from django.urls import reverse


# Create your views here.
def index(request):
    images_list = Image.objects.all()
    context = {"images_list": images_list}
    return render(request, "gallery/index.html", context)

def add_image(request):
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('images:index'))
        else:
            form = ImageForm()

        return render(request, 'gallery/image_form.html', {'form', form})

gallery/templates/gallery/image_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block content %}
        <form action="{% url 'images:addImage' %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Adicionar" />
        </form>
    {% endblock %}
</body>
</html>

gallery/templates/gallery/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Galería de imágenes</title>
</head>
<body>
    <h3>Galería de imágenes</h3>
    {% for image in images_list %}
        {% if image.imageFile == none %}
            <img src="{{ image.url }} width="300px, height="300px"/>
        {% else %}
            <img src="{{ image.imageFile }} width="300px, height="300px"/>
        {% endif %}

    {% endfor %}

</body>
</html>